export type Lake = {
  id: string;
  name: string;
  state: string;
  acres: string;
  maxDepth: string;
  county: string;
  lat: number;
  lon: number;
  usgsSiteId: string | null; // USGS gauge site near the lake
  biteLevel: number;
  species: string[];
  reports: LakeReport[];
  tackle: LakeTackle[];
};

export type LakeReport = {
  id: number;
  user: string;
  ago: string;
  species: string;
  technique: string;
  depth: string;
  rating: number;
  notes: string;
};

export type LakeTackle = {
  id: number;
  name: string;
  brand: string;
  price: string;
  rating: number;
  reviews: number;
  reason: string;
  affiliateUrl: string;
};

export const lakes: Record<string, Lake> = {
  "1": {
    id: "1",
    name: "Lake Tenkiller",
    state: "OK",
    acres: "12,900",
    maxDepth: "180ft",
    county: "Cherokee / Sequoyah",
    lat: 35.6,
    lon: -95.0,
    usgsSiteId: "07197000", // Illinois River below Tenkiller Ferry Dam
    biteLevel: 4,
    species: ["Largemouth Bass", "Smallmouth Bass", "Crappie", "Catfish", "Walleye"],
    reports: [
      {
        id: 1,
        user: "TroublinTrout",
        ago: "2h ago",
        species: "Bass",
        technique: "Topwater frogs",
        depth: "2–4ft",
        rating: 4,
        notes: "Schooling on the north end near the bluffs. Top frogs working great at first light. Missed a lot but landed 6 keeper bass.",
      },
      {
        id: 2,
        user: "OkieBasser",
        ago: "Yesterday",
        species: "Largemouth Bass",
        technique: "Swimbait slow roll",
        depth: "8–12ft",
        rating: 3,
        notes: "Decent afternoon bite on the main lake points. Water clearing up after last week's rain.",
      },
    ],
    tackle: [
      { id: 1, name: "BOOYAH Pad Crasher Frog", brand: "BOOYAH", price: "$8.99", rating: 4.7, reviews: 1243, reason: "Bass hitting topwater frogs right now", affiliateUrl: "#" },
      { id: 2, name: "Zoom Horny Toad", brand: "Zoom", price: "$5.49", rating: 4.5, reviews: 891, reason: "Walking bait producing in the shallows", affiliateUrl: "#" },
      { id: 3, name: "Strike King KVD 1.5 Crankbait", brand: "Strike King", price: "$11.49", rating: 4.8, reviews: 876, reason: "Reaction bite on the main lake points", affiliateUrl: "#" },
    ],
  },
  "2": {
    id: "2",
    name: "Grand Lake",
    state: "OK",
    acres: "46,500",
    maxDepth: "120ft",
    county: "Delaware / Mayes / Ottawa",
    lat: 36.5,
    lon: -95.0,
    usgsSiteId: "07185000", // Neosho River at Commerce
    biteLevel: 5,
    species: ["Largemouth Bass", "Crappie", "Walleye", "Catfish", "White Bass"],
    reports: [
      {
        id: 1,
        user: "OkieFisher",
        ago: "4h ago",
        species: "Crappie",
        technique: "1/8oz tube jigs",
        depth: "12–18ft",
        rating: 5,
        notes: "Limits in 2 hours drifting the main channel near the bridge. Pink/chartreuse working best.",
      },
    ],
    tackle: [
      { id: 1, name: "Bobby Garland Crappie Baby", brand: "Bobby Garland", price: "$4.99", rating: 4.6, reviews: 2104, reason: "Crappie crushing jigs right now", affiliateUrl: "#" },
      { id: 2, name: "Southern Pro Tube Jig 1/8oz", brand: "Southern Pro", price: "$3.99", rating: 4.4, reviews: 654, reason: "Matching the hatch at 12–18ft", affiliateUrl: "#" },
    ],
  },
  "3": {
    id: "3",
    name: "Keystone Lake",
    state: "OK",
    acres: "26,000",
    maxDepth: "60ft",
    county: "Pawnee / Osage / Tulsa",
    lat: 36.14,
    lon: -96.3,
    usgsSiteId: "07164500", // Arkansas River below Keystone Dam
    biteLevel: 3,
    species: ["Catfish", "Largemouth Bass", "Sand Bass", "Crappie"],
    reports: [
      {
        id: 1,
        user: "CatDaddy99",
        ago: "6h ago",
        species: "Catfish",
        technique: "Cut shad, bottom rig",
        depth: "20ft",
        rating: 3,
        notes: "Slow but steady. 3 fish over 8lbs in the evening bite. Set up near the old river channel.",
      },
    ],
    tackle: [
      { id: 1, name: "Berkley Gulp! Catfish Dough", brand: "Berkley", price: "$6.99", rating: 4.4, reviews: 543, reason: "Catfish biting on bottom rigs", affiliateUrl: "#" },
      { id: 2, name: "Eagle Claw Kahle Hook 3/0", brand: "Eagle Claw", price: "$4.49", rating: 4.6, reviews: 1876, reason: "Standard bottom rig setup", affiliateUrl: "#" },
    ],
  },
  "4": {
    id: "4",
    name: "Lake Eufaula",
    state: "OK",
    acres: "102,000",
    maxDepth: "55ft",
    county: "McIntosh / Pittsburg / Haskell",
    lat: 35.3,
    lon: -95.4,
    usgsSiteId: "07249985", // Canadian River near Eufaula
    biteLevel: 3,
    species: ["Largemouth Bass", "Crappie", "Catfish", "White Bass"],
    reports: [],
    tackle: [
      { id: 1, name: "Rapala Original Floater", brand: "Rapala", price: "$9.99", rating: 4.7, reviews: 3421, reason: "Classic producer on Eufaula", affiliateUrl: "#" },
    ],
  },
  "5": {
    id: "5",
    name: "Fort Gibson Lake",
    state: "OK",
    acres: "19,200",
    maxDepth: "85ft",
    county: "Cherokee / Wagoner / Muskogee",
    lat: 35.87,
    lon: -95.2,
    usgsSiteId: "07196500", // Grand River near Langley
    biteLevel: 2,
    species: ["Largemouth Bass", "Crappie", "Catfish"],
    reports: [],
    tackle: [
      { id: 1, name: "Strike King Red Eye Shad", brand: "Strike King", price: "$8.49", rating: 4.5, reviews: 987, reason: "Lipless crank working in cooler water", affiliateUrl: "#" },
    ],
  },

  // Missouri Lakes
  "6": {
    id: "6",
    name: "Lake of the Ozarks",
    state: "MO",
    acres: "54,000",
    maxDepth: "130ft",
    county: "Camden / Miller / Morgan / Benton",
    lat: 38.17,
    lon: -92.73,
    usgsSiteId: "06926080", // Osage River at Tuscumbia, MO — water temp + gage height
    biteLevel: 4,
    species: ["Largemouth Bass", "Smallmouth Bass", "Crappie", "Catfish", "Walleye", "White Bass"],
    reports: [],
    tackle: [
      { id: 1, name: "Strike King KVD 1.5 Crankbait", brand: "Strike King", price: "$11.49", rating: 4.8, reviews: 876, reason: "Bass crushing crankbaits on main lake points", affiliateUrl: "#" },
      { id: 2, name: "Bobby Garland Crappie Baby", brand: "Bobby Garland", price: "$4.99", rating: 4.6, reviews: 2104, reason: "Crappie stacking in the coves", affiliateUrl: "#" },
    ],
  },
  "7": {
    id: "7",
    name: "Table Rock Lake",
    state: "MO",
    acres: "43,100",
    maxDepth: "150ft",
    county: "Stone / Taney",
    lat: 36.55,
    lon: -93.45,
    usgsSiteId: "07053450", // White River below Table Rock Dam near Branson — water temp
    biteLevel: 4,
    species: ["Largemouth Bass", "Smallmouth Bass", "Crappie", "Walleye", "Striped Bass"],
    reports: [],
    tackle: [
      { id: 1, name: "Rapala Original Floater", brand: "Rapala", price: "$9.99", rating: 4.7, reviews: 3421, reason: "Classic smallmouth producer on Table Rock", affiliateUrl: "#" },
      { id: 2, name: "Zoom Trick Worm", brand: "Zoom", price: "$5.99", rating: 4.6, reviews: 1543, reason: "Drop shot and shaky head working well", affiliateUrl: "#" },
    ],
  },
  "8": {
    id: "8",
    name: "Harry S. Truman Lake",
    state: "MO",
    acres: "55,600",
    maxDepth: "60ft",
    county: "Benton / Henry / Hickory / St. Clair",
    lat: 38.27,
    lon: -93.42,
    usgsSiteId: "06926510", // Osage River below Truman Dam — water temp + gage height
    biteLevel: 3,
    species: ["Largemouth Bass", "Crappie", "Catfish", "White Bass"],
    reports: [],
    tackle: [
      { id: 1, name: "Berkley PowerBait Maxscent Flatworm", brand: "Berkley", price: "$7.99", rating: 4.5, reviews: 654, reason: "Finesse presentations working on Truman", affiliateUrl: "#" },
    ],
  },
  "9": {
    id: "9",
    name: "Stockton Lake",
    state: "MO",
    acres: "24,900",
    maxDepth: "75ft",
    county: "Cedar / Dade",
    lat: 37.70,
    lon: -93.78,
    usgsSiteId: "06919000", // Sac River near Stockton, MO — gage height only (no water temp sensor)
    biteLevel: 3,
    species: ["Largemouth Bass", "Walleye", "Crappie", "Catfish"],
    reports: [],
    tackle: [
      { id: 1, name: "Rapala Jigging Rap", brand: "Rapala", price: "$10.99", rating: 4.6, reviews: 789, reason: "Walleye biting on jigging presentations", affiliateUrl: "#" },
    ],
  },
  "10": {
    id: "10",
    name: "Pomme de Terre Lake",
    state: "MO",
    acres: "7,800",
    maxDepth: "85ft",
    county: "Hickory / Polk",
    lat: 37.90,
    lon: -93.32,
    usgsSiteId: "06921070", // Pomme de Terre River near Polk, MO — gage height only (no water temp sensor)
    biteLevel: 3,
    species: ["Largemouth Bass", "Crappie", "Muskie"],
    reports: [],
    tackle: [
      { id: 1, name: "Suick Thriller Muskie Bait", brand: "Suick", price: "$24.99", rating: 4.4, reviews: 312, reason: "Muskie active on jerkbaits", affiliateUrl: "#" },
    ],
  },
  "11": {
    id: "11",
    name: "Mark Twain Lake",
    state: "MO",
    acres: "18,600",
    maxDepth: "60ft",
    county: "Monroe / Ralls / Shelby",
    lat: 39.57,
    lon: -91.97,
    usgsSiteId: "05508000", // Salt River near New London, MO — gage height only (no water temp sensor)
    biteLevel: 3,
    species: ["Largemouth Bass", "Crappie", "Catfish", "Bluegill"],
    reports: [],
    tackle: [
      { id: 1, name: "Eagle Claw Kahle Hook 3/0", brand: "Eagle Claw", price: "$4.49", rating: 4.6, reviews: 1876, reason: "Standard bottom rig for catfish", affiliateUrl: "#" },
    ],
  },

  // Iowa Lakes
  "12": {
    id: "12",
    name: "Lake Red Rock",
    state: "IA",
    acres: "19,000",
    maxDepth: "75ft",
    county: "Marion",
    lat: 41.3967,
    lon: -93.0733,
    usgsSiteId: null,
    biteLevel: 3,
    species: ["Largemouth Bass", "Smallmouth Bass", "Crappie", "Walleye", "Channel Catfish", "White Bass"],
    reports: [],
    tackle: [
      { id: 1, name: "Strike King KVD 1.5 Crankbait", brand: "Strike King", price: "$11.49", rating: 4.8, reviews: 876, reason: "Bass crushing crankbaits on main lake points", affiliateUrl: "#" },
      { id: 2, name: "Rapala Jigging Rap", brand: "Rapala", price: "$10.99", rating: 4.6, reviews: 789, reason: "Walleye biting on jigging presentations", affiliateUrl: "#" },
    ],
  },
  "13": {
    id: "13",
    name: "Saylorville Lake",
    state: "IA",
    acres: "5,900",
    maxDepth: "50ft",
    county: "Polk / Dallas",
    lat: 41.735,
    lon: -93.7317,
    usgsSiteId: null,
    biteLevel: 3,
    species: ["Largemouth Bass", "White Bass", "Crappie", "Walleye", "Channel Catfish"],
    reports: [],
    tackle: [
      { id: 1, name: "Bobby Garland Crappie Baby", brand: "Bobby Garland", price: "$4.99", rating: 4.6, reviews: 2104, reason: "Crappie stacking in the coves", affiliateUrl: "#" },
      { id: 2, name: "Zoom Trick Worm", brand: "Zoom", price: "$5.99", rating: 4.6, reviews: 1543, reason: "Finesse worm working on bass", affiliateUrl: "#" },
    ],
  },
  "14": {
    id: "14",
    name: "Spirit Lake",
    state: "IA",
    acres: "5,684",
    maxDepth: "24ft",
    county: "Dickinson",
    lat: 43.465,
    lon: -95.1017,
    usgsSiteId: null,
    biteLevel: 3,
    species: ["Walleye", "Yellow Perch", "Northern Pike", "Largemouth Bass", "Crappie"],
    reports: [],
    tackle: [
      { id: 1, name: "Rapala Original Floater", brand: "Rapala", price: "$9.99", rating: 4.7, reviews: 3421, reason: "Classic walleye and pike producer", affiliateUrl: "#" },
      { id: 2, name: "Rapala Jigging Rap", brand: "Rapala", price: "$10.99", rating: 4.6, reviews: 789, reason: "Walleye biting on jigging presentations", affiliateUrl: "#" },
    ],
  },
  "15": {
    id: "15",
    name: "West Okoboji Lake",
    state: "IA",
    acres: "3,847",
    maxDepth: "136ft",
    county: "Dickinson",
    lat: 43.3783,
    lon: -95.1533,
    usgsSiteId: null,
    biteLevel: 3,
    species: ["Walleye", "Smallmouth Bass", "Largemouth Bass", "Crappie", "Northern Pike"],
    reports: [],
    tackle: [
      { id: 1, name: "Rapala Jigging Rap", brand: "Rapala", price: "$10.99", rating: 4.6, reviews: 789, reason: "Deep walleye presentations working well", affiliateUrl: "#" },
    ],
  },
  "16": {
    id: "16",
    name: "Rathbun Lake",
    state: "IA",
    acres: "11,000",
    maxDepth: "60ft",
    county: "Appanoose",
    lat: 40.8167,
    lon: -92.8917,
    usgsSiteId: null,
    biteLevel: 3,
    species: ["Walleye", "Largemouth Bass", "Crappie", "Channel Catfish", "White Bass"],
    reports: [],
    tackle: [
      { id: 1, name: "Strike King Red Eye Shad", brand: "Strike King", price: "$8.49", rating: 4.5, reviews: 987, reason: "Lipless crank working for walleye and bass", affiliateUrl: "#" },
    ],
  },
  "17": {
    id: "17",
    name: "Coralville Lake",
    state: "IA",
    acres: "5,430",
    maxDepth: "40ft",
    county: "Johnson",
    lat: 41.72,
    lon: -91.5567,
    usgsSiteId: null,
    biteLevel: 3,
    species: ["Largemouth Bass", "Smallmouth Bass", "Crappie", "Channel Catfish", "Walleye"],
    reports: [],
    tackle: [
      { id: 1, name: "Zoom Trick Worm", brand: "Zoom", price: "$5.99", rating: 4.6, reviews: 1543, reason: "Bass on finesse presentations in clear water", affiliateUrl: "#" },
    ],
  },

  // Illinois Lakes
  "18": {
    id: "18",
    name: "Rend Lake",
    state: "IL",
    acres: "18,900",
    maxDepth: "26ft",
    county: "Jefferson / Franklin",
    lat: 38.0567,
    lon: -88.9717,
    usgsSiteId: null,
    biteLevel: 3,
    species: ["Largemouth Bass", "Crappie", "Bluegill", "Channel Catfish", "White Bass", "Walleye"],
    reports: [],
    tackle: [
      { id: 1, name: "Bobby Garland Crappie Baby", brand: "Bobby Garland", price: "$4.99", rating: 4.6, reviews: 2104, reason: "Crappie stacking under docks", affiliateUrl: "#" },
      { id: 2, name: "Strike King KVD 1.5 Crankbait", brand: "Strike King", price: "$11.49", rating: 4.8, reviews: 876, reason: "Bass on main lake structure", affiliateUrl: "#" },
    ],
  },
  "19": {
    id: "19",
    name: "Carlyle Lake",
    state: "IL",
    acres: "26,000",
    maxDepth: "35ft",
    county: "Clinton / Bond / Fayette",
    lat: 38.6133,
    lon: -89.3517,
    usgsSiteId: null,
    biteLevel: 3,
    species: ["Largemouth Bass", "White Bass", "Crappie", "Channel Catfish", "Walleye", "Hybrid Striped Bass"],
    reports: [],
    tackle: [
      { id: 1, name: "Strike King Red Eye Shad", brand: "Strike King", price: "$8.49", rating: 4.5, reviews: 987, reason: "White bass and hybrid striper slashing bait", affiliateUrl: "#" },
      { id: 2, name: "Zoom Trick Worm", brand: "Zoom", price: "$5.99", rating: 4.6, reviews: 1543, reason: "Bass producing on points and humps", affiliateUrl: "#" },
    ],
  },
  "20": {
    id: "20",
    name: "Lake Shelbyville",
    state: "IL",
    acres: "11,100",
    maxDepth: "45ft",
    county: "Shelby / Moultrie",
    lat: 39.4317,
    lon: -88.7717,
    usgsSiteId: null,
    biteLevel: 3,
    species: ["Largemouth Bass", "Crappie", "Channel Catfish", "White Bass", "Walleye"],
    reports: [],
    tackle: [
      { id: 1, name: "BOOYAH Pad Crasher Frog", brand: "BOOYAH", price: "$8.99", rating: 4.7, reviews: 1243, reason: "Bass hitting topwater in shallow coves", affiliateUrl: "#" },
    ],
  },
  "21": {
    id: "21",
    name: "Crab Orchard Lake",
    state: "IL",
    acres: "7,000",
    maxDepth: "40ft",
    county: "Williamson",
    lat: 37.7083,
    lon: -89.0017,
    usgsSiteId: null,
    biteLevel: 3,
    species: ["Largemouth Bass", "Crappie", "Bluegill", "Channel Catfish", "Flathead Catfish"],
    reports: [],
    tackle: [
      { id: 1, name: "Berkley Gulp! Catfish Dough", brand: "Berkley", price: "$6.99", rating: 4.4, reviews: 543, reason: "Catfish biting on bottom rigs", affiliateUrl: "#" },
      { id: 2, name: "Zoom Trick Worm", brand: "Zoom", price: "$5.99", rating: 4.6, reviews: 1543, reason: "Bass on finesse in clear water", affiliateUrl: "#" },
    ],
  },
  "22": {
    id: "22",
    name: "Fox Chain O' Lakes",
    state: "IL",
    acres: "6,700",
    maxDepth: "40ft",
    county: "Lake",
    lat: 42.405,
    lon: -88.1783,
    usgsSiteId: null,
    biteLevel: 3,
    species: ["Largemouth Bass", "Northern Pike", "Walleye", "Crappie", "Muskie", "Bluegill"],
    reports: [],
    tackle: [
      { id: 1, name: "Suick Thriller Muskie Bait", brand: "Suick", price: "$24.99", rating: 4.4, reviews: 312, reason: "Muskie and pike active on jerkbaits", affiliateUrl: "#" },
      { id: 2, name: "Rapala Original Floater", brand: "Rapala", price: "$9.99", rating: 4.7, reviews: 3421, reason: "Classic walleye and pike producer", affiliateUrl: "#" },
    ],
  },
  "23": {
    id: "23",
    name: "Lake Decatur",
    state: "IL",
    acres: "2,800",
    maxDepth: "21ft",
    county: "Macon",
    lat: 39.82,
    lon: -88.9083,
    usgsSiteId: null,
    biteLevel: 2,
    species: ["Largemouth Bass", "Crappie", "Channel Catfish", "Bluegill", "White Bass"],
    reports: [],
    tackle: [
      { id: 1, name: "Bobby Garland Crappie Baby", brand: "Bobby Garland", price: "$4.99", rating: 4.6, reviews: 2104, reason: "Crappie producing under structure", affiliateUrl: "#" },
    ],
  },

  // Kentucky Lakes
  "24": {
    id: "24",
    name: "Kentucky Lake",
    state: "KY",
    acres: "160,300",
    maxDepth: "65ft",
    county: "Marshall / Calloway / Trigg / Lyon / Livingston",
    lat: 36.9,
    lon: -88.2583,
    usgsSiteId: null,
    biteLevel: 4,
    species: ["Largemouth Bass", "Smallmouth Bass", "Crappie", "Striped Bass", "White Bass", "Channel Catfish", "Walleye"],
    reports: [],
    tackle: [
      { id: 1, name: "Strike King KVD 1.5 Crankbait", brand: "Strike King", price: "$11.49", rating: 4.8, reviews: 876, reason: "Bass crushing crankbaits along ledges", affiliateUrl: "#" },
      { id: 2, name: "Bobby Garland Crappie Baby", brand: "Bobby Garland", price: "$4.99", rating: 4.6, reviews: 2104, reason: "Crappie stacking on brush piles", affiliateUrl: "#" },
    ],
  },
  "25": {
    id: "25",
    name: "Lake Barkley",
    state: "KY",
    acres: "57,920",
    maxDepth: "85ft",
    county: "Trigg / Lyon / Livingston / Caldwell",
    lat: 36.8983,
    lon: -87.9433,
    usgsSiteId: null,
    biteLevel: 3,
    species: ["Largemouth Bass", "Smallmouth Bass", "Crappie", "Striped Bass", "White Bass", "Sauger"],
    reports: [],
    tackle: [
      { id: 1, name: "Zoom Trick Worm", brand: "Zoom", price: "$5.99", rating: 4.6, reviews: 1543, reason: "Finesse worm working on deeper bass", affiliateUrl: "#" },
    ],
  },
  "26": {
    id: "26",
    name: "Dale Hollow Lake",
    state: "KY",
    acres: "27,700",
    maxDepth: "149ft",
    county: "Clinton / Cumberland",
    lat: 36.5533,
    lon: -85.4183,
    usgsSiteId: null,
    biteLevel: 4,
    species: ["Smallmouth Bass", "Largemouth Bass", "Crappie", "Walleye", "Rainbow Trout", "Channel Catfish"],
    reports: [],
    tackle: [
      { id: 1, name: "Rapala Original Floater", brand: "Rapala", price: "$9.99", rating: 4.7, reviews: 3421, reason: "Smallmouth bass crushing floaters off rocky banks", affiliateUrl: "#" },
      { id: 2, name: "Zoom Trick Worm", brand: "Zoom", price: "$5.99", rating: 4.6, reviews: 1543, reason: "Drop shot deadly on deep smallmouth", affiliateUrl: "#" },
    ],
  },
  "27": {
    id: "27",
    name: "Lake Cumberland",
    state: "KY",
    acres: "50,250",
    maxDepth: "200ft",
    county: "Russell / Clinton / Wayne / Pulaski",
    lat: 36.89,
    lon: -84.9183,
    usgsSiteId: null,
    biteLevel: 4,
    species: ["Largemouth Bass", "Smallmouth Bass", "Striped Bass", "Walleye", "Crappie", "Rainbow Trout", "Brown Trout"],
    reports: [],
    tackle: [
      { id: 1, name: "Strike King Red Eye Shad", brand: "Strike King", price: "$8.49", rating: 4.5, reviews: 987, reason: "Striped bass and walleye hammering shad imitations", affiliateUrl: "#" },
      { id: 2, name: "Rapala Jigging Rap", brand: "Rapala", price: "$10.99", rating: 4.6, reviews: 789, reason: "Deep walleye and trout presentations", affiliateUrl: "#" },
    ],
  },
  "28": {
    id: "28",
    name: "Barren River Lake",
    state: "KY",
    acres: "10,000",
    maxDepth: "95ft",
    county: "Barren / Allen",
    lat: 36.9,
    lon: -86.1433,
    usgsSiteId: null,
    biteLevel: 3,
    species: ["Largemouth Bass", "Smallmouth Bass", "Crappie", "White Bass", "Channel Catfish", "Walleye"],
    reports: [],
    tackle: [
      { id: 1, name: "BOOYAH Pad Crasher Frog", brand: "BOOYAH", price: "$8.99", rating: 4.7, reviews: 1243, reason: "Bass hitting topwater in shallow areas", affiliateUrl: "#" },
    ],
  },

  // Tennessee Lakes
  "29": {
    id: "29",
    name: "Norris Lake",
    state: "TN",
    acres: "33,840",
    maxDepth: "175ft",
    county: "Union / Campbell / Claiborne / Anderson",
    lat: 36.2383,
    lon: -84.0817,
    usgsSiteId: null,
    biteLevel: 4,
    species: ["Largemouth Bass", "Smallmouth Bass", "Striped Bass", "Crappie", "Walleye", "Rainbow Trout", "Brown Trout"],
    reports: [],
    tackle: [
      { id: 1, name: "Zoom Trick Worm", brand: "Zoom", price: "$5.99", rating: 4.6, reviews: 1543, reason: "Smallmouth on drop shot in clear deep water", affiliateUrl: "#" },
      { id: 2, name: "Strike King Red Eye Shad", brand: "Strike King", price: "$8.49", rating: 4.5, reviews: 987, reason: "Striped bass chasing shad on main lake", affiliateUrl: "#" },
    ],
  },
  "30": {
    id: "30",
    name: "Cherokee Lake",
    state: "TN",
    acres: "30,300",
    maxDepth: "175ft",
    county: "Jefferson / Grainger / Hamblen / Hawkins",
    lat: 36.1967,
    lon: -83.4967,
    usgsSiteId: null,
    biteLevel: 3,
    species: ["Largemouth Bass", "Smallmouth Bass", "Crappie", "Striped Bass", "Walleye", "Channel Catfish"],
    reports: [],
    tackle: [
      { id: 1, name: "Strike King KVD 1.5 Crankbait", brand: "Strike King", price: "$11.49", rating: 4.8, reviews: 876, reason: "Bass on main lake points and ledges", affiliateUrl: "#" },
    ],
  },
  "31": {
    id: "31",
    name: "Reelfoot Lake",
    state: "TN",
    acres: "15,000",
    maxDepth: "18ft",
    county: "Lake / Obion",
    lat: 36.4367,
    lon: -89.36,
    usgsSiteId: null,
    biteLevel: 4,
    species: ["Crappie", "Bluegill", "Largemouth Bass", "Channel Catfish", "Yellow Bass"],
    reports: [],
    tackle: [
      { id: 1, name: "Bobby Garland Crappie Baby", brand: "Bobby Garland", price: "$4.99", rating: 4.6, reviews: 2104, reason: "Famous crappie lake — jigs producing all day", affiliateUrl: "#" },
      { id: 2, name: "Southern Pro Tube Jig 1/8oz", brand: "Southern Pro", price: "$3.99", rating: 4.4, reviews: 654, reason: "Slow troll tubes through cypress trees", affiliateUrl: "#" },
    ],
  },
  "32": {
    id: "32",
    name: "Center Hill Lake",
    state: "TN",
    acres: "18,220",
    maxDepth: "195ft",
    county: "DeKalb / Smith / White / Cannon",
    lat: 36.0933,
    lon: -85.7867,
    usgsSiteId: null,
    biteLevel: 4,
    species: ["Smallmouth Bass", "Largemouth Bass", "Walleye", "Crappie", "Rainbow Trout", "Brown Trout"],
    reports: [],
    tackle: [
      { id: 1, name: "Rapala Original Floater", brand: "Rapala", price: "$9.99", rating: 4.7, reviews: 3421, reason: "Smallmouth and trout on floaters near rocky banks", affiliateUrl: "#" },
    ],
  },
  "33": {
    id: "33",
    name: "Percy Priest Lake",
    state: "TN",
    acres: "14,200",
    maxDepth: "80ft",
    county: "Davidson / Rutherford / Wilson",
    lat: 36.1467,
    lon: -86.5733,
    usgsSiteId: null,
    biteLevel: 3,
    species: ["Largemouth Bass", "Smallmouth Bass", "Spotted Bass", "Crappie", "Striped Bass", "Channel Catfish"],
    reports: [],
    tackle: [
      { id: 1, name: "BOOYAH Pad Crasher Frog", brand: "BOOYAH", price: "$8.99", rating: 4.7, reviews: 1243, reason: "Topwater bass bite active near Nashville", affiliateUrl: "#" },
      { id: 2, name: "Zoom Trick Worm", brand: "Zoom", price: "$5.99", rating: 4.6, reviews: 1543, reason: "Drop shot producing on spotted bass", affiliateUrl: "#" },
    ],
  },

  // Arkansas Lakes
  "34": {
    id: "34",
    name: "Lake Ouachita",
    state: "AR",
    acres: "48,300",
    maxDepth: "200ft",
    county: "Garland / Montgomery / Saline",
    lat: 34.5533,
    lon: -93.1983,
    usgsSiteId: null,
    biteLevel: 4,
    species: ["Largemouth Bass", "Smallmouth Bass", "Striped Bass", "Spotted Bass", "Crappie", "Walleye", "Channel Catfish"],
    reports: [],
    tackle: [
      { id: 1, name: "Zoom Trick Worm", brand: "Zoom", price: "$5.99", rating: 4.6, reviews: 1543, reason: "Finesse working on clear deep water bass", affiliateUrl: "#" },
      { id: 2, name: "Strike King Red Eye Shad", brand: "Strike King", price: "$8.49", rating: 4.5, reviews: 987, reason: "Striped bass chasing shad on main lake", affiliateUrl: "#" },
    ],
  },
  "35": {
    id: "35",
    name: "Beaver Lake",
    state: "AR",
    acres: "28,370",
    maxDepth: "200ft",
    county: "Benton / Carroll / Madison / Washington",
    lat: 36.4383,
    lon: -93.9033,
    usgsSiteId: null,
    biteLevel: 4,
    species: ["Largemouth Bass", "Smallmouth Bass", "Striped Bass", "Crappie", "Walleye", "Channel Catfish"],
    reports: [],
    tackle: [
      { id: 1, name: "Rapala Original Floater", brand: "Rapala", price: "$9.99", rating: 4.7, reviews: 3421, reason: "Smallmouth crushing floaters on rocky banks", affiliateUrl: "#" },
      { id: 2, name: "Bobby Garland Crappie Baby", brand: "Bobby Garland", price: "$4.99", rating: 4.6, reviews: 2104, reason: "Crappie stacking on submerged timber", affiliateUrl: "#" },
    ],
  },
  "36": {
    id: "36",
    name: "Norfork Lake",
    state: "AR",
    acres: "22,000",
    maxDepth: "175ft",
    county: "Baxter / Fulton / Izard",
    lat: 36.4383,
    lon: -92.2217,
    usgsSiteId: null,
    biteLevel: 3,
    species: ["Largemouth Bass", "Smallmouth Bass", "Striped Bass", "Crappie", "Walleye", "Channel Catfish"],
    reports: [],
    tackle: [
      { id: 1, name: "Strike King KVD 1.5 Crankbait", brand: "Strike King", price: "$11.49", rating: 4.8, reviews: 876, reason: "Bass on ledges and main lake points", affiliateUrl: "#" },
    ],
  },
  "37": {
    id: "37",
    name: "Bull Shoals Lake",
    state: "AR",
    acres: "45,440",
    maxDepth: "220ft",
    county: "Marion / Baxter / Boone",
    lat: 36.3617,
    lon: -92.58,
    usgsSiteId: null,
    biteLevel: 4,
    species: ["Largemouth Bass", "Smallmouth Bass", "Striped Bass", "Crappie", "Walleye", "Channel Catfish"],
    reports: [],
    tackle: [
      { id: 1, name: "Zoom Trick Worm", brand: "Zoom", price: "$5.99", rating: 4.6, reviews: 1543, reason: "Deep finesse producing on clear water bass", affiliateUrl: "#" },
      { id: 2, name: "Rapala Jigging Rap", brand: "Rapala", price: "$10.99", rating: 4.6, reviews: 789, reason: "Walleye on deep jigging presentations", affiliateUrl: "#" },
    ],
  },
  "38": {
    id: "38",
    name: "Lake Dardanelle",
    state: "AR",
    acres: "34,300",
    maxDepth: "45ft",
    county: "Pope / Yell / Logan / Franklin",
    lat: 35.2317,
    lon: -93.2483,
    usgsSiteId: null,
    biteLevel: 3,
    species: ["Largemouth Bass", "Crappie", "Bluegill", "Channel Catfish", "Flathead Catfish", "White Bass", "Striped Bass"],
    reports: [],
    tackle: [
      { id: 1, name: "Berkley Gulp! Catfish Dough", brand: "Berkley", price: "$6.99", rating: 4.4, reviews: 543, reason: "Catfish active on bottom rigs in the shallows", affiliateUrl: "#" },
      { id: 2, name: "Bobby Garland Crappie Baby", brand: "Bobby Garland", price: "$4.99", rating: 4.6, reviews: 2104, reason: "Crappie stacking on brush piles and timber", affiliateUrl: "#" },
    ],
  },
  "39": {
    id: "39",
    name: "Millwood Lake",
    state: "AR",
    acres: "29,500",
    maxDepth: "40ft",
    county: "Little River / Sevier / Miller",
    lat: 33.7217,
    lon: -94.0433,
    usgsSiteId: null,
    biteLevel: 4,
    species: ["Largemouth Bass", "Crappie", "Bluegill", "Channel Catfish", "Flathead Catfish"],
    reports: [],
    tackle: [
      { id: 1, name: "BOOYAH Pad Crasher Frog", brand: "BOOYAH", price: "$8.99", rating: 4.7, reviews: 1243, reason: "Giant bass crushing topwater in heavy cover", affiliateUrl: "#" },
      { id: 2, name: "Strike King KVD 1.5 Crankbait", brand: "Strike King", price: "$11.49", rating: 4.8, reviews: 876, reason: "Bass on main lake points and ledges", affiliateUrl: "#" },
    ],
  },

  // Kansas Lakes
  "40": {
    id: "40",
    name: "Milford Lake",
    state: "KS",
    acres: "15,700",
    maxDepth: "50ft",
    county: "Geary / Clay / Riley",
    lat: 39.08,
    lon: -96.9167,
    usgsSiteId: null,
    biteLevel: 3,
    species: ["Largemouth Bass", "Smallmouth Bass", "White Bass", "Walleye", "Crappie", "Channel Catfish", "Wiper"],
    reports: [],
    tackle: [
      { id: 1, name: "Rapala Jigging Rap", brand: "Rapala", price: "$10.99", rating: 4.6, reviews: 789, reason: "Walleye biting on jigging presentations", affiliateUrl: "#" },
      { id: 2, name: "Strike King Red Eye Shad", brand: "Strike King", price: "$8.49", rating: 4.5, reviews: 987, reason: "Wiper and white bass chasing shad", affiliateUrl: "#" },
    ],
  },
  "41": {
    id: "41",
    name: "Cheney Reservoir",
    state: "KS",
    acres: "9,537",
    maxDepth: "50ft",
    county: "Reno / Kingman / Sedgwick",
    lat: 37.7667,
    lon: -97.8117,
    usgsSiteId: null,
    biteLevel: 3,
    species: ["Walleye", "Largemouth Bass", "White Bass", "Wiper", "Crappie", "Channel Catfish"],
    reports: [],
    tackle: [
      { id: 1, name: "Rapala Original Floater", brand: "Rapala", price: "$9.99", rating: 4.7, reviews: 3421, reason: "Walleye producing at dawn and dusk", affiliateUrl: "#" },
    ],
  },
  "42": {
    id: "42",
    name: "Tuttle Creek Lake",
    state: "KS",
    acres: "12,500",
    maxDepth: "40ft",
    county: "Riley / Pottawatomie / Marshall",
    lat: 39.33,
    lon: -96.5883,
    usgsSiteId: null,
    biteLevel: 3,
    species: ["Largemouth Bass", "White Bass", "Walleye", "Crappie", "Channel Catfish", "Wiper"],
    reports: [],
    tackle: [
      { id: 1, name: "Strike King KVD 1.5 Crankbait", brand: "Strike King", price: "$11.49", rating: 4.8, reviews: 876, reason: "Bass and walleye on main lake structure", affiliateUrl: "#" },
    ],
  },
  "43": {
    id: "43",
    name: "Perry Lake",
    state: "KS",
    acres: "12,250",
    maxDepth: "50ft",
    county: "Jefferson / Jackson",
    lat: 39.12,
    lon: -95.4333,
    usgsSiteId: null,
    biteLevel: 3,
    species: ["Largemouth Bass", "Smallmouth Bass", "Crappie", "White Bass", "Walleye", "Channel Catfish"],
    reports: [],
    tackle: [
      { id: 1, name: "Zoom Trick Worm", brand: "Zoom", price: "$5.99", rating: 4.6, reviews: 1543, reason: "Finesse working on largemouth in clear coves", affiliateUrl: "#" },
    ],
  },
  "44": {
    id: "44",
    name: "Clinton Lake",
    state: "KS",
    acres: "7,000",
    maxDepth: "50ft",
    county: "Douglas / Shawnee",
    lat: 38.935,
    lon: -95.3633,
    usgsSiteId: null,
    biteLevel: 3,
    species: ["Largemouth Bass", "Smallmouth Bass", "White Bass", "Crappie", "Walleye", "Channel Catfish", "Wiper"],
    reports: [],
    tackle: [
      { id: 1, name: "Bobby Garland Crappie Baby", brand: "Bobby Garland", price: "$4.99", rating: 4.6, reviews: 2104, reason: "Crappie producing on submerged brush", affiliateUrl: "#" },
    ],
  },

  // Nebraska Lakes
  "45": {
    id: "45",
    name: "Lake McConaughy",
    state: "NE",
    acres: "55,000",
    maxDepth: "142ft",
    county: "Keith",
    lat: 41.2317,
    lon: -101.775,
    usgsSiteId: null,
    biteLevel: 4,
    species: ["Striped Bass", "Walleye", "Largemouth Bass", "Smallmouth Bass", "White Bass", "Yellow Perch", "Rainbow Trout", "Channel Catfish"],
    reports: [],
    tackle: [
      { id: 1, name: "Strike King Red Eye Shad", brand: "Strike King", price: "$8.49", rating: 4.5, reviews: 987, reason: "Striped bass and walleye crushing shad imitations", affiliateUrl: "#" },
      { id: 2, name: "Rapala Original Floater", brand: "Rapala", price: "$9.99", rating: 4.7, reviews: 3421, reason: "Walleye and trout on floaters near inlets", affiliateUrl: "#" },
    ],
  },
  "46": {
    id: "46",
    name: "Harlan County Lake",
    state: "NE",
    acres: "13,250",
    maxDepth: "65ft",
    county: "Harlan / Franklin",
    lat: 40.0583,
    lon: -99.21,
    usgsSiteId: null,
    biteLevel: 3,
    species: ["Walleye", "Largemouth Bass", "White Bass", "Crappie", "Channel Catfish", "Wiper"],
    reports: [],
    tackle: [
      { id: 1, name: "Rapala Jigging Rap", brand: "Rapala", price: "$10.99", rating: 4.6, reviews: 789, reason: "Walleye on jigging presentations", affiliateUrl: "#" },
    ],
  },
  "47": {
    id: "47",
    name: "Lewis & Clark Lake",
    state: "NE",
    acres: "31,000",
    maxDepth: "35ft",
    county: "Cedar",
    lat: 42.855,
    lon: -97.4767,
    usgsSiteId: null,
    biteLevel: 3,
    species: ["Walleye", "Sauger", "Smallmouth Bass", "Channel Catfish", "White Bass", "Crappie", "Northern Pike"],
    reports: [],
    tackle: [
      { id: 1, name: "Rapala Jigging Rap", brand: "Rapala", price: "$10.99", rating: 4.6, reviews: 789, reason: "Walleye and sauger on jigging rigs", affiliateUrl: "#" },
      { id: 2, name: "Eagle Claw Kahle Hook 3/0", brand: "Eagle Claw", price: "$4.49", rating: 4.6, reviews: 1876, reason: "Channel cat on bottom rigs in current", affiliateUrl: "#" },
    ],
  },
  "48": {
    id: "48",
    name: "Merritt Reservoir",
    state: "NE",
    acres: "2,906",
    maxDepth: "72ft",
    county: "Cherry",
    lat: 42.6133,
    lon: -100.8433,
    usgsSiteId: null,
    biteLevel: 3,
    species: ["Walleye", "Largemouth Bass", "Northern Pike", "Channel Catfish", "Crappie", "Tiger Muskie"],
    reports: [],
    tackle: [
      { id: 1, name: "Suick Thriller Muskie Bait", brand: "Suick", price: "$24.99", rating: 4.4, reviews: 312, reason: "Tiger muskie and pike active on jerkbaits", affiliateUrl: "#" },
    ],
  },

  // Texas Lakes
  "49": {
    id: "49",
    name: "Sam Rayburn Reservoir",
    state: "TX",
    acres: "114,500",
    maxDepth: "75ft",
    county: "Angelina / Sabine / San Augustine / Jasper",
    lat: 31.07,
    lon: -94.1167,
    usgsSiteId: null,
    biteLevel: 5,
    species: ["Largemouth Bass", "Crappie", "Bluegill", "Channel Catfish", "White Bass"],
    reports: [],
    tackle: [
      { id: 1, name: "BOOYAH Pad Crasher Frog", brand: "BOOYAH", price: "$8.99", rating: 4.7, reviews: 1243, reason: "Giant bass crushing topwater in shallow timber", affiliateUrl: "#" },
      { id: 2, name: "Strike King KVD 1.5 Crankbait", brand: "Strike King", price: "$11.49", rating: 4.8, reviews: 876, reason: "Bass on main lake ledges and points", affiliateUrl: "#" },
    ],
  },
  "50": {
    id: "50",
    name: "Toledo Bend Reservoir",
    state: "TX",
    acres: "185,000",
    maxDepth: "110ft",
    county: "Sabine / Newton / Shelby / Panola",
    lat: 31.2,
    lon: -93.5883,
    usgsSiteId: null,
    biteLevel: 5,
    species: ["Largemouth Bass", "Crappie", "Bluegill", "Channel Catfish", "White Bass", "Hybrid Striped Bass"],
    reports: [],
    tackle: [
      { id: 1, name: "BOOYAH Pad Crasher Frog", brand: "BOOYAH", price: "$8.99", rating: 4.7, reviews: 1243, reason: "Trophy bass crushing topwater in heavy cover", affiliateUrl: "#" },
      { id: 2, name: "Zoom Trick Worm", brand: "Zoom", price: "$5.99", rating: 4.6, reviews: 1543, reason: "Big bass on deep finesse presentations", affiliateUrl: "#" },
    ],
  },
  "51": {
    id: "51",
    name: "Lake Fork",
    state: "TX",
    acres: "27,690",
    maxDepth: "70ft",
    county: "Wood / Rains / Hopkins",
    lat: 32.9183,
    lon: -95.59,
    usgsSiteId: null,
    biteLevel: 5,
    species: ["Largemouth Bass", "Crappie", "Bluegill", "Channel Catfish"],
    reports: [],
    tackle: [
      { id: 1, name: "Strike King KVD 1.5 Crankbait", brand: "Strike King", price: "$11.49", rating: 4.8, reviews: 876, reason: "World-class bass lake — crankbaits producing on ledges", affiliateUrl: "#" },
      { id: 2, name: "Zoom Trick Worm", brand: "Zoom", price: "$5.99", rating: 4.6, reviews: 1543, reason: "Big bass on worms near submerged timber", affiliateUrl: "#" },
    ],
  },
  "52": {
    id: "52",
    name: "Lake Texoma",
    state: "TX",
    acres: "93,080",
    maxDepth: "100ft",
    county: "Grayson / Cooke",
    lat: 33.8383,
    lon: -96.6217,
    usgsSiteId: null,
    biteLevel: 4,
    species: ["Striped Bass", "Largemouth Bass", "Smallmouth Bass", "Crappie", "White Bass", "Channel Catfish", "Sauger"],
    reports: [],
    tackle: [
      { id: 1, name: "Strike King Red Eye Shad", brand: "Strike King", price: "$8.49", rating: 4.5, reviews: 987, reason: "Striped bass crushing shad imitations on main lake", affiliateUrl: "#" },
      { id: 2, name: "Bobby Garland Crappie Baby", brand: "Bobby Garland", price: "$4.99", rating: 4.6, reviews: 2104, reason: "Crappie producing on brush piles", affiliateUrl: "#" },
    ],
  },
  "53": {
    id: "53",
    name: "Lake Travis",
    state: "TX",
    acres: "18,930",
    maxDepth: "210ft",
    county: "Travis / Burnet",
    lat: 30.4017,
    lon: -97.9,
    usgsSiteId: null,
    biteLevel: 3,
    species: ["Largemouth Bass", "Smallmouth Bass", "Striped Bass", "White Bass", "Crappie", "Catfish"],
    reports: [],
    tackle: [
      { id: 1, name: "Zoom Trick Worm", brand: "Zoom", price: "$5.99", rating: 4.6, reviews: 1543, reason: "Bass on finesse in clear Hill Country water", affiliateUrl: "#" },
    ],
  },
  "54": {
    id: "54",
    name: "Lake Conroe",
    state: "TX",
    acres: "21,400",
    maxDepth: "75ft",
    county: "Montgomery / Walker",
    lat: 30.3817,
    lon: -95.5733,
    usgsSiteId: null,
    biteLevel: 4,
    species: ["Largemouth Bass", "Crappie", "Bluegill", "Channel Catfish", "Striped Bass", "White Bass"],
    reports: [],
    tackle: [
      { id: 1, name: "BOOYAH Pad Crasher Frog", brand: "BOOYAH", price: "$8.99", rating: 4.7, reviews: 1243, reason: "Bass hitting topwater in shallow grass", affiliateUrl: "#" },
      { id: 2, name: "Bobby Garland Crappie Baby", brand: "Bobby Garland", price: "$4.99", rating: 4.6, reviews: 2104, reason: "Crappie stacking on timber and brush", affiliateUrl: "#" },
    ],
  },
  "55": {
    id: "55",
    name: "Lake Buchanan",
    state: "TX",
    acres: "23,060",
    maxDepth: "132ft",
    county: "Llano / Burnet / San Saba",
    lat: 30.7583,
    lon: -98.405,
    usgsSiteId: null,
    biteLevel: 3,
    species: ["Largemouth Bass", "Smallmouth Bass", "Striped Bass", "White Bass", "Crappie", "Catfish", "Guadalupe Bass"],
    reports: [],
    tackle: [
      { id: 1, name: "Strike King Red Eye Shad", brand: "Strike King", price: "$8.49", rating: 4.5, reviews: 987, reason: "Striped bass and white bass chasing shad", affiliateUrl: "#" },
    ],
  },
  "56": {
    id: "56",
    name: "Amistad Reservoir",
    state: "TX",
    acres: "64,900",
    maxDepth: "220ft",
    county: "Val Verde",
    lat: 29.465,
    lon: -101.06,
    usgsSiteId: null,
    biteLevel: 4,
    species: ["Largemouth Bass", "Smallmouth Bass", "Striped Bass", "Flathead Catfish", "Blue Catfish", "Channel Catfish", "White Bass"],
    reports: [],
    tackle: [
      { id: 1, name: "Zoom Trick Worm", brand: "Zoom", price: "$5.99", rating: 4.6, reviews: 1543, reason: "Bass on finesse in ultra-clear water", affiliateUrl: "#" },
      { id: 2, name: "Berkley Gulp! Catfish Dough", brand: "Berkley", price: "$6.99", rating: 4.4, reviews: 543, reason: "Giant catfish on bottom rigs in deep water", affiliateUrl: "#" },
    ],
  },
};
